export const STOCK_LIST = [
  { symbol: "AAPL", name: "Apple" },
  { symbol: "TSLA", name: "Tesla" },
  { symbol: "MSFT", name: "Microsoft" },
  { symbol: "GOOGL", name: "Alphabet" },
  { symbol: "AMZN", name: "Amazon" },
  { symbol: "NVDA", name: "Nvidia" },
  { symbol: "META", name: "Meta Platforms" },
  { symbol: "NFLX", name: "Netflix" },
  { symbol: "AMD", name: "AMD" },
  { symbol: "INTC", name: "Intel" },
  { symbol: "DIS", name: "Disney" },
  { symbol: "KO", name: "Coca-Cola" },
  { symbol: "PEP", name: "PepsiCo" },
  { symbol: "NKE", name: "Nike" },
  { symbol: "BA", name: "Boeing" },
  { symbol: "V", name: "Visa" },
  { symbol: "MA", name: "Mastercard" },
  { symbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "BAC", name: "Bank of America" },
  { symbol: "WMT", name: "Walmart" },
  { symbol: "SBUX", name: "Starbucks" },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "UBER", name: "Uber" },
  { symbol: "ABNB", name: "Airbnb" },
  { symbol: "COIN", name: "Coinbase" },
  { symbol: "PLTR", name: "Palantir" },
  { symbol: "SHOP", name: "Shopify" },
  { symbol: "ORCL", name: "Oracle" },
  { symbol: "ADBE", name: "Adobe" },
  { symbol: "CRM", name: "Salesforce" },
];