export const STOCK_LIST = [
  // ABD hisseleri
  { symbol: "AAPL", apiSymbol: "AAPL", name: "Apple" },
  { symbol: "TSLA", apiSymbol: "TSLA", name: "Tesla" },
  { symbol: "MSFT", apiSymbol: "MSFT", name: "Microsoft" },
  { symbol: "GOOGL", apiSymbol: "GOOGL", name: "Alphabet" },
  { symbol: "AMZN", apiSymbol: "AMZN", name: "Amazon" },
  { symbol: "NVDA", apiSymbol: "NVDA", name: "Nvidia" },
  { symbol: "META", apiSymbol: "META", name: "Meta Platforms" },
  { symbol: "NFLX", apiSymbol: "NFLX", name: "Netflix" },
  { symbol: "AMD", apiSymbol: "AMD", name: "AMD" },
  { symbol: "INTC", apiSymbol: "INTC", name: "Intel" },
  { symbol: "DIS", apiSymbol: "DIS", name: "Disney" },
  { symbol: "KO", apiSymbol: "KO", name: "Coca-Cola" },
  { symbol: "PEP", apiSymbol: "PEP", name: "PepsiCo" },
  { symbol: "NKE", apiSymbol: "NKE", name: "Nike" },
  { symbol: "BA", apiSymbol: "BA", name: "Boeing" },
  { symbol: "V", apiSymbol: "V", name: "Visa" },
  { symbol: "MA", apiSymbol: "MA", name: "Mastercard" },
  { symbol: "JPM", apiSymbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "BAC", apiSymbol: "BAC", name: "Bank of America" },
  { symbol: "WMT", apiSymbol: "WMT", name: "Walmart" },
  { symbol: "SBUX", apiSymbol: "SBUX", name: "Starbucks" },
  { symbol: "PYPL", apiSymbol: "PYPL", name: "PayPal" },
  { symbol: "UBER", apiSymbol: "UBER", name: "Uber" },
  { symbol: "ABNB", apiSymbol: "ABNB", name: "Airbnb" },
  { symbol: "COIN", apiSymbol: "COIN", name: "Coinbase" },
  { symbol: "PLTR", apiSymbol: "PLTR", name: "Palantir" },
  { symbol: "SHOP", apiSymbol: "SHOP", name: "Shopify" },
  { symbol: "ORCL", apiSymbol: "ORCL", name: "Oracle" },
  { symbol: "ADBE", apiSymbol: "ADBE", name: "Adobe" },
  { symbol: "CRM", apiSymbol: "CRM", name: "Salesforce" },

  // Borsa Istanbul (BIST) hisseleri
  { symbol: "THYAO", apiSymbol: "THYAO.IS", name: "Turk Hava Yollari" },
  { symbol: "ASELS", apiSymbol: "ASELS.IS", name: "Aselsan" },
  { symbol: "GARAN", apiSymbol: "GARAN.IS", name: "Garanti BBVA" },
  { symbol: "AKBNK", apiSymbol: "AKBNK.IS", name: "Akbank" },
  { symbol: "YKBNK", apiSymbol: "YKBNK.IS", name: "Yapi Kredi" },
  { symbol: "ISCTR", apiSymbol: "ISCTR.IS", name: "Is Bankasi" },
  { symbol: "HALKB", apiSymbol: "HALKB.IS", name: "Halkbank" },
  { symbol: "SASA", apiSymbol: "SASA.IS", name: "Sasa Polyester" },
  { symbol: "KCHOL", apiSymbol: "KCHOL.IS", name: "Koc Holding" },
  { symbol: "SAHOL", apiSymbol: "SAHOL.IS", name: "Sabanci Holding" },
  { symbol: "EREGL", apiSymbol: "EREGL.IS", name: "Eregli Demir Celik" },
  { symbol: "BIMAS", apiSymbol: "BIMAS.IS", name: "BIM Magazalar" },
  { symbol: "TUPRS", apiSymbol: "TUPRS.IS", name: "Tupras" },
  { symbol: "PGSUS", apiSymbol: "PGSUS.IS", name: "Pegasus Havayollari" },
  { symbol: "SISE", apiSymbol: "SISE.IS", name: "Sise Cam" },
  { symbol: "FROTO", apiSymbol: "FROTO.IS", name: "Ford Otosan" },
  { symbol: "TOASO", apiSymbol: "TOASO.IS", name: "Tofas" },
  { symbol: "VESTL", apiSymbol: "VESTL.IS", name: "Vestel" },
  { symbol: "KOZAL", apiSymbol: "KOZAL.IS", name: "Koza Altin" },
  { symbol: "TCELL", apiSymbol: "TCELL.IS", name: "Turkcell" },
  { symbol: "PETKM", apiSymbol: "PETKM.IS", name: "Petkim" },
];